#!/usr/bin/env bash
set -euo pipefail
cd /workspace/apps/api
go mod verify
go vet -p=1 ./...
go test -race -p=1 -count=1 ./...
go test -p=1 -tags=integration -run '^$' ./...
go test -p=1 -tags=integration,authfixture -run '^$' ./...
